version: "2"

run:
  go: "1.26.2"

linters:
  enable:
    - govet        # підозрілі конструкції
    - errcheck     # незамінені помилки
    - staticcheck  # статичний аналіз
    - ineffassign  # марні присвоєння
    - unused       # невикористаний код
    - misspell     # орфографія в коментарях
  exclusions:
    paths:
      - web/node_modules
      - .*\.db$
    rules:
      - path: _test\.go
        linters:
          - errcheck   # у тестах можна ігнорувати деякі помилки

formatters:
  enable:
    - goimports    # порядок імпортів
  settings:
    goimports:
      local-prefixes:
        - github.com/ZaViBiS/isitdead
  exclusions:
    paths:
      - web/node_modules
      - .*\.db$
